### ISSUE TITLE
Reverse proxy and WCF

### ISSUE THREAD

**Issue by IrvinDominin** [SharpTools/SharpReverseProxy#10]
Hi, thanks fot this great library.

We are facing an issue using SharpReverseProxy to proxy a call on a WCF SOAP service. eg
`https://proxy.demo.com/myWCF.svc --> http://192.10.1.1/myWCF.svc`

the client breaks because the url present in the request and in the SOAP envelope is altered by the reverse proxy; how can we handle this?

**Comment by andrecarlucci** [comment]
Hi @IrvinDominin ,

I never used it with SOAP to be honest.
Do you thing you could use the `ResponseModifier` of the `ProxyRule` and use a Regex or String.Replace to also modify the SOAP envelope of the Response body?

**Comment by samusaran** [comment]
Hi @andrecarlucci , I work with @IrvinDominin.

We actually used both the Request Modifier and the ResponseModifier to let the reverse proxy and the service talk with success.
Our issue is about our .net application crashing upon receiving the response for the proxy, because the specified URL (proxy's one) and the URL of the service are different.

While this issue is not directly related to your middleware, maybe there is some configuration or practice that we are missing.

Thanks.

**Comment by andrecarlucci** [comment]
That's weird, there is no point for the client to break if it has no idea that the final URL is different.
Are you using a generated client from the original service?

If you can provide a repro somewhere, I can take a look :)

**Comment by IrvinDominin** [comment]
Hi @andrecarlucci you point us in the right direction; thanks to @samusaran we have solved the issue!

The code was almost done, but a pesky RegEx, combined with our infernal corporate proxy was driving us crazy
